name: biti_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  google_fonts: ^4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RedHatDisplay-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 800
        - asset: assets/fonts/RedHatDisplay-Black.ttf
          weight: 900

